### ISSUE TITLE
Thanks for the good work!

### ISSUE THREAD

**Issue by trialforce** [gsaurus/sor_pancakes#1]
Hi man!

First I want to thank you for the good work in this project.

Can you help me changing the Sprites from Galsia? 

It says "compressed" in the APP.

There is a comunity in some place where I can get help about SOR hack/mod?

**Comment by gsaurus** [comment]
Enemies are compressed in the original SoR2 ROM, and PK2 doesn't support writing in compressed format.
I recommend using the SoR2 Syndicate Wars hack in which all characters are uncompressed (and so, editable).
