### ISSUE TITLE
pancakes guide

### ISSUE THREAD

**Issue by terriadle** [gsaurus/sor_pancakes#2]
Can you please give me a guide file for the new Syndicate Wars (the one with the kangaroo)?

**Comment by gsaurus** [comment]
Yes! Thanks for reminding me about this.
There was a branch with pk2 1.6b, from reverse engineered sources because I lost the original (anything older than v1.5). Decided to merge it to master now. Find the guides here:
https://github.com/gsaurus/sor_pancakes/tree/master/pk2/guides
