### ISSUE TITLE
Can't use decompress art despite rom being loaded.

### ISSUE THREAD

**Issue by Pacsonic** [gsaurus/sor_pancakes#3]
I am trying to edit the select screen and I need to extract the select screen but the option for decompressing art is still faded. It's like this even when I am on a compressed sprite. What's the fix to this?

**Comment by gsaurus** [comment]
Hi Pacsonic, thanks for reaching out.

I couldn't reproduce the issue. Do you have more information on this?

**Comment by showeycm** [comment]
https://user-images.githubusercontent.com/114880468/198551844-b3fc8594-5527-4a6b-8e93-a89e069fa0e2.mp4
same thing happening to me, wanted to edit character portraits which requires using decompress feature which doesn't work.

**Comment by gsaurus** [comment]
I see. I don't remember why the feature was disabled. It's now re-enabled.
